on:
  push:
    branches: [ master ]
    tags: ['v*', 'pybuild*']
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install protoc
        env:
          PROTOC_VERSION: "3.19.4"
          PROTOC_ZIP: "protoc-3.19.4-linux-x86_64.zip"
        run: wget https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP && sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc && sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*' && rm -f $PROTOC_ZIP
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build
        run: mkdir generated && protoc -I src --python_betterproto_out=generated/ src/*.proto src/service/*.proto
